/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoEditorRouteImport } from './routes/video-editor'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as TtsRouteImport } from './routes/tts'
import { Route as SmartToolsRouteImport } from './routes/smart-tools'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProductCompositionRouteImport } from './routes/product-composition'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as PhotoRepairRouteImport } from './routes/photo-repair'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as IdPhotoRouteImport } from './routes/id-photo'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as EcommerceWorkflowRouteImport } from './routes/ecommerce-workflow'
import { Route as EcommerceAmazonRouteImport } from './routes/ecommerce-amazon'
import { Route as EcommerceRouteImport } from './routes/ecommerce'
import { Route as Director3dRouteImport } from './routes/director-3d'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgentSquadRouteImport } from './routes/agent-squad'
import { Route as IndexRouteImport } from './routes/index'

const VideoEditorRoute = VideoEditorRouteImport.update({
  id: '/video-editor',
  path: '/video-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const TtsRoute = TtsRouteImport.update({
  id: '/tts',
  path: '/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartToolsRoute = SmartToolsRouteImport.update({
  id: '/smart-tools',
  path: '/smart-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCompositionRoute = ProductCompositionRouteImport.update({
  id: '/product-composition',
  path: '/product-composition',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoRepairRoute = PhotoRepairRouteImport.update({
  id: '/photo-repair',
  path: '/photo-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const IdPhotoRoute = IdPhotoRouteImport.update({
  id: '/id-photo',
  path: '/id-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceWorkflowRoute = EcommerceWorkflowRouteImport.update({
  id: '/ecommerce-workflow',
  path: '/ecommerce-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceAmazonRoute = EcommerceAmazonRouteImport.update({
  id: '/ecommerce-amazon',
  path: '/ecommerce-amazon',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const Director3dRoute = Director3dRouteImport.update({
  id: '/director-3d',
  path: '/director-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSquadRoute = AgentSquadRouteImport.update({
  id: '/agent-squad',
  path: '/agent-squad',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-squad': typeof AgentSquadRoute
  '/agents': typeof AgentsRoute
  '/backup': typeof BackupRoute
  '/canvas': typeof CanvasRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/conversations': typeof ConversationsRoute
  '/director-3d': typeof Director3dRoute
  '/ecommerce': typeof EcommerceRoute
  '/ecommerce-amazon': typeof EcommerceAmazonRoute
  '/ecommerce-workflow': typeof EcommerceWorkflowRoute
  '/favorites': typeof FavoritesRoute
  '/generate': typeof GenerateRoute
  '/id-photo': typeof IdPhotoRoute
  '/memory': typeof MemoryRoute
  '/photo-repair': typeof PhotoRepairRoute
  '/plugins': typeof PluginsRoute
  '/product-composition': typeof ProductCompositionRoute
  '/prompts': typeof PromptsRoute
  '/queue': typeof QueueRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/smart-tools': typeof SmartToolsRoute
  '/tts': typeof TtsRoute
  '/usage': typeof UsageRoute
  '/video-editor': typeof VideoEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-squad': typeof AgentSquadRoute
  '/agents': typeof AgentsRoute
  '/backup': typeof BackupRoute
  '/canvas': typeof CanvasRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/conversations': typeof ConversationsRoute
  '/director-3d': typeof Director3dRoute
  '/ecommerce': typeof EcommerceRoute
  '/ecommerce-amazon': typeof EcommerceAmazonRoute
  '/ecommerce-workflow': typeof EcommerceWorkflowRoute
  '/favorites': typeof FavoritesRoute
  '/generate': typeof GenerateRoute
  '/id-photo': typeof IdPhotoRoute
  '/memory': typeof MemoryRoute
  '/photo-repair': typeof PhotoRepairRoute
  '/plugins': typeof PluginsRoute
  '/product-composition': typeof ProductCompositionRoute
  '/prompts': typeof PromptsRoute
  '/queue': typeof QueueRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/smart-tools': typeof SmartToolsRoute
  '/tts': typeof TtsRoute
  '/usage': typeof UsageRoute
  '/video-editor': typeof VideoEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-squad': typeof AgentSquadRoute
  '/agents': typeof AgentsRoute
  '/backup': typeof BackupRoute
  '/canvas': typeof CanvasRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/conversations': typeof ConversationsRoute
  '/director-3d': typeof Director3dRoute
  '/ecommerce': typeof EcommerceRoute
  '/ecommerce-amazon': typeof EcommerceAmazonRoute
  '/ecommerce-workflow': typeof EcommerceWorkflowRoute
  '/favorites': typeof FavoritesRoute
  '/generate': typeof GenerateRoute
  '/id-photo': typeof IdPhotoRoute
  '/memory': typeof MemoryRoute
  '/photo-repair': typeof PhotoRepairRoute
  '/plugins': typeof PluginsRoute
  '/product-composition': typeof ProductCompositionRoute
  '/prompts': typeof PromptsRoute
  '/queue': typeof QueueRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/smart-tools': typeof SmartToolsRoute
  '/tts': typeof TtsRoute
  '/usage': typeof UsageRoute
  '/video-editor': typeof VideoEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-squad'
    | '/agents'
    | '/backup'
    | '/canvas'
    | '/chat'
    | '/community'
    | '/conversations'
    | '/director-3d'
    | '/ecommerce'
    | '/ecommerce-amazon'
    | '/ecommerce-workflow'
    | '/favorites'
    | '/generate'
    | '/id-photo'
    | '/memory'
    | '/photo-repair'
    | '/plugins'
    | '/product-composition'
    | '/prompts'
    | '/queue'
    | '/research'
    | '/settings'
    | '/skills'
    | '/smart-tools'
    | '/tts'
    | '/usage'
    | '/video-editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-squad'
    | '/agents'
    | '/backup'
    | '/canvas'
    | '/chat'
    | '/community'
    | '/conversations'
    | '/director-3d'
    | '/ecommerce'
    | '/ecommerce-amazon'
    | '/ecommerce-workflow'
    | '/favorites'
    | '/generate'
    | '/id-photo'
    | '/memory'
    | '/photo-repair'
    | '/plugins'
    | '/product-composition'
    | '/prompts'
    | '/queue'
    | '/research'
    | '/settings'
    | '/skills'
    | '/smart-tools'
    | '/tts'
    | '/usage'
    | '/video-editor'
  id:
    | '__root__'
    | '/'
    | '/agent-squad'
    | '/agents'
    | '/backup'
    | '/canvas'
    | '/chat'
    | '/community'
    | '/conversations'
    | '/director-3d'
    | '/ecommerce'
    | '/ecommerce-amazon'
    | '/ecommerce-workflow'
    | '/favorites'
    | '/generate'
    | '/id-photo'
    | '/memory'
    | '/photo-repair'
    | '/plugins'
    | '/product-composition'
    | '/prompts'
    | '/queue'
    | '/research'
    | '/settings'
    | '/skills'
    | '/smart-tools'
    | '/tts'
    | '/usage'
    | '/video-editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentSquadRoute: typeof AgentSquadRoute
  AgentsRoute: typeof AgentsRoute
  BackupRoute: typeof BackupRoute
  CanvasRoute: typeof CanvasRoute
  ChatRoute: typeof ChatRoute
  CommunityRoute: typeof CommunityRoute
  ConversationsRoute: typeof ConversationsRoute
  Director3dRoute: typeof Director3dRoute
  EcommerceRoute: typeof EcommerceRoute
  EcommerceAmazonRoute: typeof EcommerceAmazonRoute
  EcommerceWorkflowRoute: typeof EcommerceWorkflowRoute
  FavoritesRoute: typeof FavoritesRoute
  GenerateRoute: typeof GenerateRoute
  IdPhotoRoute: typeof IdPhotoRoute
  MemoryRoute: typeof MemoryRoute
  PhotoRepairRoute: typeof PhotoRepairRoute
  PluginsRoute: typeof PluginsRoute
  ProductCompositionRoute: typeof ProductCompositionRoute
  PromptsRoute: typeof PromptsRoute
  QueueRoute: typeof QueueRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  SmartToolsRoute: typeof SmartToolsRoute
  TtsRoute: typeof TtsRoute
  UsageRoute: typeof UsageRoute
  VideoEditorRoute: typeof VideoEditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-editor': {
      id: '/video-editor'
      path: '/video-editor'
      fullPath: '/video-editor'
      preLoaderRoute: typeof VideoEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tts': {
      id: '/tts'
      path: '/tts'
      fullPath: '/tts'
      preLoaderRoute: typeof TtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-tools': {
      id: '/smart-tools'
      path: '/smart-tools'
      fullPath: '/smart-tools'
      preLoaderRoute: typeof SmartToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-composition': {
      id: '/product-composition'
      path: '/product-composition'
      fullPath: '/product-composition'
      preLoaderRoute: typeof ProductCompositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-repair': {
      id: '/photo-repair'
      path: '/photo-repair'
      fullPath: '/photo-repair'
      preLoaderRoute: typeof PhotoRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/id-photo': {
      id: '/id-photo'
      path: '/id-photo'
      fullPath: '/id-photo'
      preLoaderRoute: typeof IdPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce-workflow': {
      id: '/ecommerce-workflow'
      path: '/ecommerce-workflow'
      fullPath: '/ecommerce-workflow'
      preLoaderRoute: typeof EcommerceWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce-amazon': {
      id: '/ecommerce-amazon'
      path: '/ecommerce-amazon'
      fullPath: '/ecommerce-amazon'
      preLoaderRoute: typeof EcommerceAmazonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director-3d': {
      id: '/director-3d'
      path: '/director-3d'
      fullPath: '/director-3d'
      preLoaderRoute: typeof Director3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-squad': {
      id: '/agent-squad'
      path: '/agent-squad'
      fullPath: '/agent-squad'
      preLoaderRoute: typeof AgentSquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentSquadRoute: AgentSquadRoute,
  AgentsRoute: AgentsRoute,
  BackupRoute: BackupRoute,
  CanvasRoute: CanvasRoute,
  ChatRoute: ChatRoute,
  CommunityRoute: CommunityRoute,
  ConversationsRoute: ConversationsRoute,
  Director3dRoute: Director3dRoute,
  EcommerceRoute: EcommerceRoute,
  EcommerceAmazonRoute: EcommerceAmazonRoute,
  EcommerceWorkflowRoute: EcommerceWorkflowRoute,
  FavoritesRoute: FavoritesRoute,
  GenerateRoute: GenerateRoute,
  IdPhotoRoute: IdPhotoRoute,
  MemoryRoute: MemoryRoute,
  PhotoRepairRoute: PhotoRepairRoute,
  PluginsRoute: PluginsRoute,
  ProductCompositionRoute: ProductCompositionRoute,
  PromptsRoute: PromptsRoute,
  QueueRoute: QueueRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  SmartToolsRoute: SmartToolsRoute,
  TtsRoute: TtsRoute,
  UsageRoute: UsageRoute,
  VideoEditorRoute: VideoEditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
